["TATASTEEL.NS", "ICICIBANK.NS", "HDFCBANK.NS", "SBIN.NS", "NTPC.NS", "AXISBANK.NS"],
["POWERGRID.NS", "ITC.NS", "RELIANCE.NS", "BHARTIARTL.NS", "BPCL.NS", "TATAMOTORS.NS"], 
["KOTAKBANK.NS", "COALINDIA.NS", "WIPRO.NS", "HINDALCO.NS", "INDUSINDBK.NS", "INFY.NS"], 
["HDFCLIFE.NS", "M&M.NS", "ADANIPORTS.NS", "SUNPHARMA.NS", "LT.NS", "ADANIENT.NS", "CIPLA.NS"],
["IDEA.NS", "YESBANK.NS", "PNB.NS", "HFCL.NS","INDUSTOWER.NS", "SAIL.NS", "INDIACEM.NS", "NHPC.NS"],
["UJJIVANSFB.NS", "BHEL.NS", "CANBK.NS", "GMRINFRA.NS"],
["ZOMATO.NS"]

[
  ["KINGFA.NS", "SRGHFL.NS", "STCINDIA.NS", "DLINKINDIA.NS"],
  ["SHIVALIK.NS", "GMBREW.NS", "CREATIVE.NS", "CASTROLIND.NS"],
  ["IZMO.NS", "THEINVEST.NS", "ONEPOINT.NS", "DCM.NS"],
  ["HUDCO.NS", "GPPL.NS", "ZYDUSWELL.NS", "BOROLTD.NS"],
  ["SOTL.NS", "PONNIERODE.NS", "HARSHA.NS", "SGIL.NS"],
  ["PYRAMID.NS", "EMAMIPAP.NS", "PRAKASH.NS", "TVSSRICH.NS"],
  ["PITTIEING.NS"]
]

