["TATASTEEL", "ICICIBANK", "HDFCBANK", "SBIN", "NTPC", "AXISBANK"],
["POWERGRID", "ITC", "RELIANCE", "BHARTIARTL", "BPCL", "TATAMOTORS"], 
["KOTAKBANK", "COALINDIA", "WIPRO", "HINDALCO", "INDUSINDBK", "INFY"], 
["HDFCLIFE", "M&M", "ADANIPORTS", "SUNPHARMA", "LT", "ADANIENT", "CIPLA"],
["IDEA", "YESBANK", "PNB", "HFCL","INDUSTOWER", "SAIL", "INDIACEM", "NHPC"],
["UJJIVANSFB", "BHEL", "CANBK", "GMRINFRA"],
["ZOMATO"]

[
  ["KINGFA", "SRGHFL", "STCINDIA", "DLINKINDIA"],
  ["SHIVALIK", "GMBREW", "CREATIVE", "CASTROLIND"],
  ["IZMO", "THEINVEST", "ONEPOINT", "DCM"],
  ["HUDCO", "GPPL", "ZYDUSWELL", "BOROLTD"],
  ["SOTL", "PONNIERODE", "HARSHA", "SGIL"],
  ["PYRAMID", "EMAMIPAP", "PRAKASH", "TVSSRICH"],
  ["PITTIEING"]
]